### ISSUE TITLE
./mach configure fails with mozilla/newapp

### ISSUE THREAD

**Issue by ajvincent** [ajvincent/mozilla-newapp#1]
These steps might not be exact, but they're pretty close.  Close enough where anyone who already has mozilla-central and this repository checked out should be able to do simple copies and reproduce this.

## Steps to reproduce
```bash
pushd ~
mkdir newapp-cleandir
cd newapp-cleandir
hg clone https://hg.mozilla.org/mozilla-central/
git clone git@github.com:ajvincent/mozilla-newapp.git gh-newapp
ln -s -r gh-newapp mozilla-central/newapp # creates a link to reference the newapp
echo -e "\nnewapp" >> mozilla-central/.hgignore
export MOZCONFIG=~/newapp-cleandir/gh-newapp/newapp-sym.mozconfig
cd mozilla-central
./mach configure
```

## Exception
```
 0:16.20 Traceback (most recent call last):
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/configure.py", line 229, in <module>
 0:16.20     sys.exit(main(sys.argv))
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/configure.py", line 85, in main
 0:16.20     return config_status(config)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/configure.py", line 224, in config_status
 0:16.20     return config_status(args=[], **sanitized_config)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/config_status.py", line 177, in config_status
 0:16.20     the_backend.consume(definitions)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/base.py", line 146, in consume
 0:16.20     self.consume_finished()
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 1022, in consume_finished
 0:16.20     self._fill_root_mk()
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 738, in _fill_root_mk
 0:16.20     main, all_deps = self._traversal.compute_dependencies(filter)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 294, in compute_dependencies
 0:16.20     return recurse(""), deps
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 285, in recurse
 0:16.20     nodes = recurse(node, prev_nodes)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 285, in recurse
 0:16.20     nodes = recurse(node, prev_nodes)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 285, in recurse
 0:16.20     nodes = recurse(node, prev_nodes)
 0:16.20   [Previous line repeated 983 more times]
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 276, in recurse
 0:16.20     current, parallel, sequential = self.call_filter(start_node, filter)
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 250, in call_filter
 0:16.20     return filter(current, self.get_subdirs(current))
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 320, in get_subdirs
 0:16.20     result = self._traversal.get(dir, self.SubDirectories())
 0:16.20   File "/home/ajvincent/newapp-cleandir/mozilla-central/python/mozbuild/mozbuild/backend/recursivemake.py", line 218, in __new__
 0:16.20     return RecursiveMakeTraversal.SubDirectoriesTuple.__new__(self, [], [])
 0:16.20   File "<string>", line 1, in <lambda>
 0:16.20 RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by ajvincent** [comment]
I traced this to app.mozbuild, where `CONFIG['MOZ_BRANDING_DIRECTORY']` is probably empty.
